import json
import logging
import os
from typing import Any, Dict, List
from langchain_core.messages import AIMessage, HumanMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
from app.graph.state import AgentState
from app.graph import ws as _ws
from app.core.mcp_client import call_mcp_tool_once

logger = logging.getLogger(__name__)


async def _call_knowledge_tool(tool_name: str, params: Dict[str, Any]) -> str:
    """
    공용 MCP 서버의 knowledge tool 을 호출하고 결과 텍스트만 반환한다.
    실패 시 ReAct 에이전트가 읽고 재시도/대안 판단할 수 있는 오류 문자열을 돌려준다.
    """
    result_text, status, error_type, error_msg = await call_mcp_tool_once(tool_name, params)
    if status != "success":
        logger.warning("MCP knowledge tool 실패: %s (%s) — %s", tool_name, error_type, error_msg)
        return f"[{tool_name} 실패: {error_type or 'error'}] {error_msg}"
    return result_text


@tool
async def vector_rag_search(query: str) -> str:
    """
    Search for vehicle manual information using Vector RAG (Qdrant).
    Best for: General questions about the manual, usage instructions, or FAQs.
    """
    return await _call_knowledge_tool("vector_rag_search", {"query": query})


@tool
async def graph_rag_search(query: str, entities: List[str] = None) -> str:
    """
    Search for relational information using Graph RAG (Neo4j).
    Best for: Multi-hop reasoning like "What components are related to this warning light?" or "Maintenance interval for a part".
    """
    return await _call_knowledge_tool(
        "graph_rag_search", {"query": query, "entities": entities or []}
    )


@tool
async def text_to_sql_query(query: str) -> str:
    """
    Query structured vehicle telemetry or maintenance history from the database (Text2SQL).
    Best for: Data retrieval like "What was my average speed?" or "Last oil change date".
    """
    return await _call_knowledge_tool("text_to_sql_query", {"query": query})

KNOWLEDGE_SYSTEM_PROMPT = """You are the Knowledge Agent in the On-Device Multimodal Driving Copilot system.
Your role is to act as the primary knowledge hub, retrieving information from various sources to answer user queries or fulfill plans delegated by the Supervisor.

Available Tools:
1. vector_rag_search: Use for standard manual queries (e.g., "What does this button do?").
2. graph_rag_search: Use for relational queries (e.g., "Engine warning light components and maintenance").
3. text_to_sql_query: Use for database lookups (e.g., "Total mileage this month", "Recent DTC codes").

Workflow:
- Read the current plan and the user's request.
- Decide which tool(s) are needed. You may need to call multiple tools if the query is complex (e.g., Context Fusion of Vector + Graph).
- If the search result is poor, try reformulating the query (CRAG approach).
- Synthesize the retrieved context into a clear, concise, and helpful response.
"""

async def knowledge_node(state: AgentState) -> Dict[str, Any]:
    await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": "Knowledge agent retrieving context..."}))
    
    messages = state.get("messages", [])
    plan = state.get("plan", [])
    context_data = state.get("context_data", {})

    # CRAG 재검색 여부: transform_query_node 가 채운 refined_query 가 있으면
    # 동일 plan 스텝을 재작성된 쿼리로 재검색하는 중이다.
    refined_query = context_data.get("refined_query", "")
    is_reretrieval = bool(refined_query)

    # 1. Prepare Instructions based on Plan-and-Execute pattern
    instruction_text = ""
    if is_reretrieval:
        instruction_text = refined_query
    elif plan and len(plan) > 0:
        instruction_text = f"Execute the next step in the plan: {plan[0]}"
    else:
        instruction_text = "Answer the user's latest query based on your domain knowledge tools."

    instruction_msg = HumanMessage(content=f"[Supervisor Instruction] {instruction_text}")
    
    # 2. Setup LLM & Tools (G1: Executor uses Qwen2.5 1.5B)
    # KNOWLEDGE_MODEL 로 오버라이드 가능 — 1.5B는 tool calling 미지원이라
    # 평가/운영 시 tool-capable 모델(예: qwen3-vl:4b-instruct)로 교체할 수 있다.
    knowledge_model = os.getenv("KNOWLEDGE_MODEL", "qwen2.5:1.5b")
    llm = ChatOpenAI(model=knowledge_model, temperature=0.1)
    tools = [vector_rag_search, graph_rag_search, text_to_sql_query]
    
    agent = create_react_agent(llm, tools, prompt=KNOWLEDGE_SYSTEM_PROMPT)
    
    messages_to_pass = messages + [instruction_msg]
    
    try:
        # 3. Invoke the ReAct Agent
        response = await agent.ainvoke({"messages": messages_to_pass})
        
        # Extract new messages generated by the Knowledge Agent
        new_messages = response["messages"][len(messages_to_pass):]
        
        # Extract the final answer (the last AI message)
        final_answer = new_messages[-1].content if new_messages else "Knowledge retrieval completed."
        
        # Context data update (accumulate findings)
        context_data["last_knowledge_result"] = final_answer
        # refined_query 는 이번 재검색으로 소비됐으므로 초기화(빈 문자열=없음).
        context_data["refined_query"] = ""

        if is_reretrieval:
            # CRAG 재검색: 동일 스텝을 다시 검색한 것이므로 plan 을 재-pop 하지 않고,
            # grade/transform 의 평가 기준(crag_query)도 원본 스텝 그대로 유지한다.
            new_plan = plan
        else:
            # 신규 스텝 실행: 완료 스텝 pop + CRAG 재검색 예산 리셋.
            # grade_retrieval/transform_query 가 "실제로 실행된 쿼리"를 평가하도록
            # crag_query 를 기록한다 — pop 이후 plan[0] 이 다음 스텝으로 바뀌어
            # grader 가 엉뚱한 스텝을 평가하는 문제를 막는다.
            user_query = next(
                (m.content for m in reversed(messages) if isinstance(m, HumanMessage)), ""
            )
            context_data["crag_query"] = plan[0] if plan else user_query
            new_plan = plan[1:] if plan else []
            context_data["crag_attempts"] = 0
        
        await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": "Knowledge retrieval complete. Returning to Supervisor."}))
        
        return {
            "messages": new_messages,
            "plan": new_plan,
            "context_data": context_data,
            "next_agent": "supervisor", # Always return control to supervisor
            "error_count": state.get("error_count", {})
        }
        
    except Exception as e:
        logger.error(f"Error in Knowledge Agent Node: {e}")
        error_count = state.get("error_count", {})
        error_count["parameter"] = error_count.get("parameter", 0) + 1
        
        await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": f"Knowledge agent failed: {str(e)[:50]}..."}))
        
        return {
            "messages": [AIMessage(content=f"Knowledge Agent encountered an error: {e}")],
            # 재검색 중 실패해도 refined_query 를 반드시 초기화한다 — 남겨두면 다음
            # knowledge 위임이 낡은 refined_query 를 재검색으로 오인해 엉뚱한
            # instruction 을 쓰고 plan 스텝 pop 을 건너뛴다.
            "context_data": {"refined_query": ""},
            "next_agent": "supervisor",
            "error_count": error_count,
            "feedback": f"Knowledge Agent failed to execute the plan step due to: {e}"
        }
