import json
import logging
from typing import Any, Dict, List
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
from app.graph.state import AgentState
from app.graph import ws as _ws
from app.core.mcp_client import call_mcp_tool_once

logger = logging.getLogger(__name__)


async def _call_knowledge_tool(tool_name: str, params: Dict[str, Any]) -> str:
    """
    공용 MCP 서버의 knowledge tool 을 호출하고 결과 텍스트만 반환한다.
    실패 시 ReAct 에이전트가 읽고 재시도/대안 판단할 수 있는 오류 문자열을 돌려준다.
    """
    result_text, status, error_type, error_msg = await call_mcp_tool_once(tool_name, params)
    if status != "success":
        logger.warning("MCP knowledge tool 실패: %s (%s) — %s", tool_name, error_type, error_msg)
        return f"[{tool_name} 실패: {error_type or 'error'}] {error_msg}"
    return result_text


@tool
async def vector_rag_search(query: str) -> str:
    """
    Search for vehicle manual information using Vector RAG (Qdrant).
    Best for: General questions about the manual, usage instructions, or FAQs.
    """
    return await _call_knowledge_tool("vector_rag_search", {"query": query})


@tool
async def graph_rag_search(query: str, entities: List[str] = None) -> str:
    """
    Search for relational information using Graph RAG (Neo4j).
    Best for: Multi-hop reasoning like "What components are related to this warning light?" or "Maintenance interval for a part".
    """
    return await _call_knowledge_tool(
        "graph_rag_search", {"query": query, "entities": entities or []}
    )


@tool
async def text_to_sql_query(query: str) -> str:
    """
    Query structured vehicle telemetry or maintenance history from the database (Text2SQL).
    Best for: Data retrieval like "What was my average speed?" or "Last oil change date".
    """
    return await _call_knowledge_tool("text_to_sql_query", {"query": query})

KNOWLEDGE_SYSTEM_PROMPT = """You are the Knowledge Agent in the On-Device Multimodal Driving Copilot system.
Your role is to act as the primary knowledge hub, retrieving information from various sources to answer user queries or fulfill plans delegated by the Supervisor.

Available Tools:
1. vector_rag_search: Use for standard manual queries (e.g., "What does this button do?").
2. graph_rag_search: Use for relational queries (e.g., "Engine warning light components and maintenance").
3. text_to_sql_query: Use for database lookups (e.g., "Total mileage this month", "Recent DTC codes").

Workflow:
- Read the current plan and the user's request.
- Decide which tool(s) are needed. You may need to call multiple tools if the query is complex (e.g., Context Fusion of Vector + Graph).
- If the search result is poor, try reformulating the query (CRAG approach).
- Synthesize the retrieved context into a clear, concise, and helpful response.
"""

async def knowledge_node(state: AgentState) -> Dict[str, Any]:
    await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": "Knowledge agent retrieving context..."}))
    
    messages = state.get("messages", [])
    plan = state.get("plan", [])
    
    # 1. Prepare Instructions based on Plan-and-Execute pattern
    instruction_text = ""
    if plan and len(plan) > 0:
        instruction_text = f"Execute the next step in the plan: {plan[0]}"
    else:
        instruction_text = "Answer the user's latest query based on your domain knowledge tools."
        
    instruction_msg = HumanMessage(content=f"[Supervisor Instruction] {instruction_text}")
    
    # 2. Setup LLM & Tools (G1: Executor uses Qwen2-VL 1.5B)
    llm = ChatOpenAI(model="qwen2-vl-1.5b-instruct-int4", temperature=0.1)
    tools = [vector_rag_search, graph_rag_search, text_to_sql_query]
    
    agent = create_react_agent(llm, tools, prompt=KNOWLEDGE_SYSTEM_PROMPT)
    
    messages_to_pass = messages + [instruction_msg]
    
    try:
        # 3. Invoke the ReAct Agent
        response = await agent.ainvoke({"messages": messages_to_pass})
        
        # Extract new messages generated by the Knowledge Agent
        new_messages = response["messages"][len(messages_to_pass):]
        
        # Extract the final answer (the last AI message)
        final_answer = new_messages[-1].content if new_messages else "Knowledge retrieval completed."
        
        # Context data update (accumulate findings)
        context_data = state.get("context_data", {})
        context_data["last_knowledge_result"] = final_answer
        
        # Pop the completed plan step
        new_plan = plan[1:] if plan else []
        
        await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": "Knowledge retrieval complete. Returning to Supervisor."}))
        
        return {
            "messages": new_messages,
            "plan": new_plan,
            "context_data": context_data,
            "next_agent": "supervisor", # Always return control to supervisor
            "error_count": state.get("error_count", {})
        }
        
    except Exception as e:
        logger.error(f"Error in Knowledge Agent Node: {e}")
        error_count = state.get("error_count", {})
        error_count["parameter"] = error_count.get("parameter", 0) + 1
        
        await _ws.websocket_manager.send_status(json.dumps({"type": "status", "data": f"Knowledge agent failed: {str(e)[:50]}..."}))
        
        return {
            "messages": [AIMessage(content=f"Knowledge Agent encountered an error: {e}")],
            "next_agent": "supervisor",
            "error_count": error_count,
            "feedback": f"Knowledge Agent failed to execute the plan step due to: {e}"
        }
